spring:
   profiles:
      active: local
      
   jpa:
      open-in-view: false
      #show-sql: true
      hibernate:
         ddl-auto: none
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         use-new-id-generator-mappings: false
      properties:
         hibernate:
            format_sql: true
            #show_sql: true
            #use_sql_comments: true
            enable_lazy_load_no_trans: true
            globally_quoted_identifiers: true
            #globally_quoted_identifiers_skip_column_definitions: true

   task:
      scheduling:
         pool:
            size: 3 # add/change/send schedule
         thread-name-prefix: schdl-pool-
         
#spring:
   #output:
   #ansi:
      #enabled: DETECT

server:
   port: 2848
   shutdown: graceful
   tomcat:
      connection-timeout: 30000
      max-threads: 100
      min-spare-threads: 50
      accept-count: 50
      uri-encoding: UTF-8

ehdtjr:
   app:
      name: upbit-server
      id: 0
   http-client:
      conn-timeout: 5000
      read-timeout: 5000
      pool-size: 50
      route-size: 20
   task:
      initial-delay-schedule: 10000
      do-trade-schedule: 60000 # fixed delay(ms)
   trade:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
      market: KRW-MVL
      ratio: 1   # +-5%
      base-price: 20    # KRW
      unit: 0.1   # 거래 단위, 0 보다 큰 경우 적용
      decimal-places: 10.0   # 거래 단위, 소수점 N자리 표현 -> .. 0.01(100의 자리까지 표현), 0.1(10의 자리까지 표현), 1.0(1의 자리까지 표현), 10.0(소수점 첫째자리까지 표현), 100.0(소수점 둘째자리까지 표현)..
   
logging:
   file:
      #path: C:\temp\logs
      #name: upbit.log
      name: C:\temp\logs\upbit.log
   # rolling is default setup of logback
   #pattern:
      #rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}
      # %line and %method are speed issue 
      #console: "%clr(%d){yellow} %clr(%-5level) ${PID} --- [%thread] %clr(%-40.40logger{39}){cyan}(%line) : %msg%n%throwable"
      #file: "%d %-5level [%thread] %logger : %msg%n" 
   level:
      com.ehdtjr.toy: debug
      org.springframework.boot.autoconfigure: info #disable CONDITIONS EVALUATION REPORT
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
   logback:
      rollingpolicy:
         max-history: 180 #The number of days to keep log archives (defaults to 7)


upbit:
   host-v1: https://api.upbit.com/v1
   url:
      #
      # EXCHANGE API
      # 자산
      get-accounts: /accounts   # 전체 계좌 조회
      # 주문
      get-orders-chance: /orders/chance   # 주문 가능 정보
      get-order: /order   # 개별 주문 조회
      get-orders: /orders   # 주문 리스트 조회
      delete-orders: /order   # 주문 취소 접수
      post-orders: /orders   # 주문하기
      # 출금
      # 입금
      # 서비스 정보
      
      #
      # QUOTATION API
      get-ticker: /ticker   # 현재가 정보

      
